name: demo
on:
  workflow_dispatch:
  push:
    branches:
      - 'demo**'
    tags-ignore:
      - '**'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          npm ci
          npm run build
      - name: full options
        uses: ./
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "testing"
          username: Build
          avatar_url: "https://github.com/dothq.png"
      - name: no content
        uses: ./
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: Build
          avatar_url: "https://github.com/dothq.png"