name: Release
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm test
      - run: npm run release
      - name: Release
        run: |
          git config --global user.name "dothq-robot"
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"
          git status
          git add lib node_modules
          git commit -m "✨ Add built code"
          git push origin master
